// TYPES IN THIS FILE ARE COPIED FROM ORIGINAL "bowser-elevators-site" PROJECT
// AFTER MAKING CHANGES IN ORIGINAL PROJECT UPDATE THIS TYPES TO SYNCHRONIZE DATA


export type ElevatorDisplayTypes = 'MLMLCD' | 'TIM2' | "7SEGMENT_NEW" | "7SEGMENT_OLD" | "TL-D70";